version: "3.9"
services:
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend_test
    stdin_open: true
    depends_on:
      - api 
    ports:
      - "8080:80"

  api:
    build:
      dockerfile: Dockerfile
      context: ./backend_test
