name: Test authentication
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository
          uses: actions/checkout@v3.6.0

        - name: 'Log into Azure using github secret AZURE_CREDENTIALS'
          uses: Azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true

        - name: 'Run az commands'
          run: |
            az account show
            az group list